version: '3.8'
services:
  app:
    image: darkwind8/github_runner:v0.0.2
    privileged: true
    environment:
      TOKEN: "${TOKEN:-forregistrytoken}"
      TOKEN_ORG: "${TOKEN_ORG:-fororgregistry}"
      ORG: "${ORG:-fororgregistry}"
      DOCKER_TLS_CERTDIR: ""
