version: '3.8'
services:
  app:
    build: .
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-buffer-size: "4m"
        mode: "non-blocking"
    environment:
      DOCKER_HOST: tcp://dind:2375
      TOKEN: "${TOKEN:-forregistrytoken}"
      TOKEN_ORG: "${TOKEN_ORG:-fororgregistry}"
      ORG: "${ORG:-fororgregistry}"
      DOCKER_TLS_CERTDIR: ""
