version: '3'
tasks:
  build:
    cmds:
      - docker build
        --tag github_runner:org
        --build-arg LABELS=darklab8,basic
        --target build-org .
      - docker build
        --tag github_runner:org-nodejs-14
        --build-arg LABELS=darklab8,nodejs-14
        --target build-org-nodejs-14 .
      - task: tag
        vars:
          TAG: "org"
      - task: tag
        vars:
          TAG: "org-nodejs-14"
    vars:
      VERSION:
        sh: git-conventional-commits version

  tag:
    cmds:
      - docker tag github_runner:{{.TAG}} darkwind8/github_runner:{{.TAG}}-latest
      - docker tag github_runner:{{.TAG}} darkwind8/github_runner:{{.TAG}}-{{.VERSION}}
    vars:
      VERSION:
        sh: git-conventional-commits version

  push:
    cmds:
      - docker push darkwind8/github_runner:{{.TAG}}-latest
      - docker push darkwind8/github_runner:{{.TAG}}-{{.VERSION}}
    vars:
      VERSION:
        sh: git-conventional-commits version

  deploy:
    cmds:
      - task: build
      - task: push
        vars:
          TAG: "org"
      - task: push
        vars:
          TAG: "org-nodejs-14"
      - task: git-tag

  git-tag:
    cmds:
      - git tag v{{.VERSION}}
      - git push origin v{{.VERSION}}
    vars:
      VERSION:
        sh: git-conventional-commits version

  version:
    cmds:
      - echo {{.VERSION}}
    vars:
      VERSION:
        sh: git-conventional-commits version

  org:launch:
    cmds:
      - defer: runuser -l user -c 'cd /app && ./config.sh remove --token {{.TOKEN}}'
      - sleep 2 && echo 'receveing token'
      - runuser -l user -c 'cd /app && ./config.sh --labels {{.LABELS}} --url {{.ORG_URL}} --token {{.TOKEN}} --unattended --disableupdate'
      - dockerd & runuser -l user -c 'cd /app && ./run.sh'
    env:
      ORG_URL: undefined
      ORG_TOKEN: undefined
      ORG_NAME: undefined
    vars:
      TOKEN:
        sh: >-
          curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer {{.ORG_TOKEN}}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/orgs/{{.ORG_NAME}}/actions/runners/registration-token | jq -r '.token'